### PR TITLE
Fixed build problem with different vue/vue-template-loader versions

### PR DESCRIPTION
**Pull request by jonny-novikov**
* Added more ignored files
* Updated vue to 2.0.8.
* Fixed reference error 'vuex-store'
* Added missed 'package'

### CODE REVIEW

**Comment by luventa** [comment]
anything wrong with vuex-store?
I've defined an alia for vuex store in webpack.base.config...and it works fine

**Comment by jonny-novikov** [comment]
@luventa Sorry, I reverted vuex-store. It was not part of the problem.

Can you add PR webhooks on travis?

**Comment by luventa** [comment]
@jonny-novikov thanks.
Sorry, I cannot do that I guess. Need wait for Fundon

**Comment by jonny-novikov** [comment]
@luventa As about aliases - it can be confusing for some users. But it works - I think it should be mentionted in 'Development' section. Because tooling/linting are confused too.

**Comment by luventa** [comment]
@jonny-novikov yes, you are right. I will make some docs for dev later.
Thanks for your advice.

**Pull request closed without merging**
